### ISSUE TITLE
game turd

### ISSUE THREAD

**Issue by Phanty133** [tomszir/olimps-liepaja-2021#2]
plz dear sirs

game look good but game lack feature

our game vs ur game:
our:
- fully peer to peer multiplayer /w lobby system
- player routing
- machine learning chatbot for question
- proper fog of war
- administrtor panel
- anti cheat and event validation using pog cryptography
- proximity-based voice chat and game chat
- skill-based gameplay
- good

you:
- comment
- good look
- challenge
- not us
- bad

thank you for reading dear sirs
plz remedy issue at earliest convenience

**Comment by tomszir** [comment]
based issue

**Comment by Phanty133** [comment]
this is bad customer support >:(((((
i will report this to the github police
